// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrvqUtXjCLVx9qAYePsEyWfX0ZkX0_aeE',
    appId: '1:183788843963:web:5be57ceac810356824ca9e',
    messagingSenderId: '183788843963',
    projectId: 'fitmate-f3e7f',
    authDomain: 'fitmate-f3e7f.firebaseapp.com',
    storageBucket: 'fitmate-f3e7f.appspot.com',
    measurementId: 'G-G65W5JK436',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGPHVSVjkFHZHWPDIGFLost2ugYm3ES4',
    appId: '1:183788843963:android:9686424f3c85c71124ca9e',
    messagingSenderId: '183788843963',
    projectId: 'fitmate-f3e7f',
    storageBucket: 'fitmate-f3e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBie_vv0-RXOmCahn6h1Etcy8Bx5072Mn8',
    appId: '1:183788843963:ios:7566632e6058541d24ca9e',
    messagingSenderId: '183788843963',
    projectId: 'fitmate-f3e7f',
    storageBucket: 'fitmate-f3e7f.appspot.com',
    iosClientId: '183788843963-vun14dvfc252ornc5ssiidbb4duhv6v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBie_vv0-RXOmCahn6h1Etcy8Bx5072Mn8',
    appId: '1:183788843963:ios:7566632e6058541d24ca9e',
    messagingSenderId: '183788843963',
    projectId: 'fitmate-f3e7f',
    storageBucket: 'fitmate-f3e7f.appspot.com',
    iosClientId: '183788843963-vun14dvfc252ornc5ssiidbb4duhv6v1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitmate',
  );
}
